apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-plain-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
      - name: my-container
        image: docker.io/kostiscodefresh/loan:latest
        env:
        - name: APP_VERSION
          value: "1.0"                                                                                                                                          
        volumeMounts:
          - name: config-volume
            mountPath: /etc/podinfo  
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080    
      volumes:
        - name: config-volume
          configMap:
            name: frontend-settings
            items:
            - key: "labels"
              path: "labels"