apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# declare ConfigMap as a resource
resources:
- rollout-fe.yml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml


# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: my-frontend-settings
  literals: 
  - APP_VERSION=2.0
  - BACKEND_HOST="backend-preview" 